version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ./tree-market:/var/www/html
    ports:
      - "8888:80"
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    volumes:
      - ./mysql-db/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
